---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-k8s-clusterrole-astronomyshop-crb
subjects:
- kind: ServiceAccount
  name: astronomy-shop-otelcol
  namespace: astronomy-shop
roleRef:
  kind: ClusterRole
  name: otel-collector-k8s-clusterrole-traces
  apiGroup: rbac.authorization.k8s.io